dist: xenial
language: cpp
sudo: required

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    -   name: Debug, Ubuntu 20.04, GCC
        os: linux
        dist: focal
        env:
          - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
          - PROJECT_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
          - COMPILER_TOOL=gcc
          - EXECUTE_TESTS=ON
          - COVERAGE=OFF # Coverage disable currently cause of huge work on features

    -   name: Debug, Ubuntu 20.04, CLang
        os: linux
        dist: focal
        env:
          - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
          - PROJECT_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
          - COMPILER_TOOL=clang
          - EXECUTE_TESTS=ON
          - COVERAGE=OFF

    -   name: Debug, Ubuntu 20.04, MinGW-W64 (without Tools)
        os: linux
        dist: focal
        env:
          - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
          - PROJECT_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off -DHG_BUILD_TOOLS=Off"
          - COMPILER_TOOL=mingw-w64
          - EXECUTE_TESTS=OFF
          - COVERAGE=OFF

    - name: Release, Ubuntu 20.04, GCC
      os: linux
      dist: focal
      env:
        - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - PROJECT_FLAGS="-DCMAKE_BUILD_TYPE=Release -DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
        - COMPILER_TOOL=gcc
        - EXECUTE_TESTS=ON
        - COVERAGE=OFF # Coverage disable currently cause of huge work on features

    - name: Release, Ubuntu 20.04, CLang
      os: linux
      dist: focal
      env:
        - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - PROJECT_FLAGS="-DCMAKE_BUILD_TYPE=Release -DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
        - COMPILER_TOOL=clang
        - EXECUTE_TESTS=ON
        - COVERAGE=OFF

    - name: Release, Ubuntu 20.04, MinGW-W64 (without Tools)
      os: linux
      dist: focal
      env:
        - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - PROJECT_FLAGS="-DCMAKE_BUILD_TYPE=Release -DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off -DHG_BUILD_TOOLS=Off"
        - COMPILER_TOOL=mingw-w64
        - EXECUTE_TESTS=OFF
        - COVERAGE=OFF

git:
  submodules: false

before_install:
  - git submodule update --init

script:
  - ${SCRIPT_PATH}