dist: xenial
language: cpp
sudo: required

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - COVERAGE=ON
        - PROJECT_FLAGS="-DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
        - COMPILER_TOOL=gcc

    - os: linux
      compiler: clang
      env:
        - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - PROJECT_FLAGS="-DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
        - COMPILER_TOOL=clang

# We'll do submodules manually, because of `--recursive`
git:
  submodules: false

before_install:
  - git submodule update --init

script:
  - ${SCRIPT_PATH}