dist: xenial
language: cpp
os: linux

services:
  - docker

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
  include:
    - name: Ubuntu, GCC
      env:
        - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - PROJECT_FLAGS="-DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
        - COMPILER_TOOL=gcc
        - EXECUTE_TESTS=ON
        - COVERAGE=ON

    - name: Ubuntu, CLang
      env:
        - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - PROJECT_FLAGS="-DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
        - COMPILER_TOOL=clang
        - EXECUTE_TESTS=ON
        - COVERAGE=OFF

    - name: Ubuntu, MinGW-W64 (without Tools)
      env:
        - SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - PROJECT_FLAGS="-DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off -DHG_BUILD_TOOLS=Off"
        - COMPILER_TOOL=mingw-w64
        - EXECUTE_TESTS=OFF
        - COVERAGE=OFF

# We'll do submodules manually, because of `--recursive`
git:
  submodules: false

before_install:
  - git submodule update --init

script:
  - echo docker run --rm -it \
      -e SCRIPT_PATH \
      -e PROJECT_FLAGS \
      -e COMPILER_TOOL \
      -e EXECUTE_TESTS \
      -e COVERAGE \
      -v "$TRAVIS_BUILD_DIR:/build/" \
      ubuntu:focal \
      /bin/bash -C "/build/$SCRIPT_PATH"

  - sudo docker run --rm -it \
        -e SCRIPT_PATH \
        -e PROJECT_FLAGS \
        -e COMPILER_TOOL \
        -e EXECUTE_TESTS \
        -e COVERAGE \
        -v "$TRAVIS_BUILD_DIR:/build/" \
        ubuntu:focal \
        /bin/bash -C "/build/$SCRIPT_PATH"