dist: xenial
language: cpp
os: linux

services:
  - docker

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
  include:
    - name: Ubuntu, GCC
      env:
        - HG_SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - HG_PROJECT_FLAGS="-DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
        - HG_COMPILER_TOOL=gcc
        - HG_EXECUTE_TESTS=ON
        - HG_COVERAGE=ON

    - name: Ubuntu, CLang
      env:
        - HG_SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - HG_PROJECT_FLAGS="-DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off"
        - HG_COMPILER_TOOL=clang
        - HG_EXECUTE_TESTS=ON
        - HG_COVERAGE=OFF

    - name: Ubuntu, MinGW-W64 (without Tools)
      env:
        - HG_SCRIPT_PATH="scripts/ci/linux/ubuntu/main.sh"
        - HG_PROJECT_FLAGS="-DHG_BUILD_TESTS=On -DHG_BUILD_EXAMPLES=On -DHG_BUILD_ALL_TESTS=On -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=Off -DHG_BUILD_TOOLS=Off"
        - HG_COMPILER_TOOL=mingw-w64
        - HG_EXECUTE_TESTS=OFF
        - HG_COVERAGE=OFF

# We'll do submodules manually, because of `--recursive`
git:
  submodules: false

before_install:
  - git submodule update --init

script:
  - env | grep HG_ > .env
  - cat .env
  - docker run \
        --env-file .env \
        -v$TRAVIS_BUILD_DIR:/build/ \
        ubuntu:focal \
        /bin/bash -C "/build/$SCRIPT_PATH"