trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    git submodule update --init

  displayName: 'Getting Submodules'

- script: |
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1E9377A2BA9EF27F &&
    sudo add-apt-repository 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main' &&
    sudo add-apt-repository 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main' &&
    sudo apt update &&
    sudo apt -y install libstdc++-8-dev libgtest-dev clang-6.0 cmake libgl1-mesa-dev libgl-dev libglu1-mesa-dev libglu-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev clang-format-9

  displayName: 'Installing Dependencies'

- script: |
    chmod +x ./scripts/check_relative_includes.sh &&
    ./scripts/check_relative_includes.sh
  displayName: 'Checking for relative includes'

- script: |
    chmod +x ./scripts/run_clang_format.sh &&
    ./scripts/run_clang_format.sh &&
    git diff -- . ':(exclude)scripts/*' | tail -n 100

  displayName: 'Checking codestyle'

- script: |
    cd /usr/src/gtest && 
    sudo CC=clang-6.0 CXX=clang++-6.0 cmake CMakeLists.txt &&
    sudo cmake --build . -- -j4 &&
    sudo cp *.a /usr/lib/ &&
    sudo mkdir /usr/local/lib/gtest &&
    sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a &&
    sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
    
  displayName: 'Setting up GTest'

- script: |
    mkdir --parent dependencies && 
    wget https://github.com/glfw/glfw/archive/3.2.1.tar.gz -q -O dependencies/glfw.tar.gz && 
    tar -xvzf dependencies/glfw.tar.gz -C dependencies/

  displayName: 'Getting External GLFW 3.2'

- script: |
    mkdir --parent dependencies && 
    wget https://github.com/nigels-com/glew/archive/glew-2.1.0.tar.gz -q -O dependencies/glew.tar.gz && 
    tar -xvzf dependencies/glew.tar.gz -C dependencies/

  displayName: 'Getting External GLEW 2.1'

- script: |
    mkdir --parent "dependencies/glfw-3.2.1/build" &&
    CC=clang-6.0 CXX=clang++-6.0 cmake -DBUILD_SHARED_LIBS=On -Bdependencies/glfw-3.2.1/build -Hdependencies/glfw-3.2.1 &&
    cmake --build dependencies/glfw-3.2.1/build -- -j4 &&
    sudo cmake --build dependencies/glfw-3.2.1/build --target install

  displayName: 'Building GLFW 3.2'

- script: |
    make -C dependencies/glew-glew-2.1.0/auto &&
    CC=clang-6.0 CXX=clang++-6.0 cmake -Bdependencies/glew-glew-2.1.0/build_dir -Hdependencies/glew-glew-2.1.0/build/cmake &&
    cmake --build dependencies/glew-glew-2.1.0/build_dir -- -j4 &&
    sudo cmake --build dependencies/glew-glew-2.1.0/build_dir --target install

  displayName: 'Building GLEW 2.1'

- script: |
    mkdir --parents cmake-build &&
    CC=clang-6.0 CXX=clang++-6.0 cmake -DHG_BUILD_TESTS=On -DHG_BUILD_ALL_TESTS=On -DHG_BUILD_EXAMPLES=On -DHGRenderingOGL_USE_GLFW=On -B"cmake-build" -H"."

  displayName: 'Configuration'

- script: |
    cd cmake-build &&
    make -j4 VERBOSE=1

  displayName: 'Building'

- script: |
    cd "cmake-build/testing" && ./HGEngineTests

  displayName: 'Testing'